flowchart LR
subgraph root.0[<center>RateLimiter<br/>1 selectors</center>]
subgraph root.0_inports[ ]
style root.0_inports fill:none,stroke:none
root.0limit[limit]
end
end
root.0_limit_FakeConstantout((10.00))
root.0_limit_FakeConstantout --> root.0limit
