package grpc

import (
	"context"

	"google.golang.org/grpc"
)

// validatorUnaryInterceptor returns a new unary server interceptors that applies defaults and validates the request
// before calling the handler.
func validatorUnaryInterceptor() grpc.UnaryServerInterceptor {
	return func(ctx context.Context, req interface{}, _ *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (resp interface{}, err error) {
		// Call Validate() on the request which was generated by protoc-gen-validate.
		if v, ok := req.(interface {
			Validate() error
		}); ok {
			if err := v.Validate(); err != nil {
				return nil, err
			}
		}
		return handler(ctx, req)
	}
}
