//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package grpc

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackoffConfig) DeepCopyInto(out *BackoffConfig) {
	*out = *in
	in.BaseDelay.DeepCopyInto(&out.BaseDelay)
	in.MaxDelay.DeepCopyInto(&out.MaxDelay)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackoffConfig.
func (in *BackoffConfig) DeepCopy() *BackoffConfig {
	if in == nil {
		return nil
	}
	out := new(BackoffConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GRPCClientConfig) DeepCopyInto(out *GRPCClientConfig) {
	*out = *in
	in.MinConnectionTimeout.DeepCopyInto(&out.MinConnectionTimeout)
	out.ClientTLSConfig = in.ClientTLSConfig
	in.Backoff.DeepCopyInto(&out.Backoff)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GRPCClientConfig.
func (in *GRPCClientConfig) DeepCopy() *GRPCClientConfig {
	if in == nil {
		return nil
	}
	out := new(GRPCClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GRPCServerConfig) DeepCopyInto(out *GRPCServerConfig) {
	*out = *in
	in.ConnectionTimeout.DeepCopyInto(&out.ConnectionTimeout)
	if in.LatencyBucketsMS != nil {
		in, out := &in.LatencyBucketsMS, &out.LatencyBucketsMS
		*out = make([]float64, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GRPCServerConfig.
func (in *GRPCServerConfig) DeepCopy() *GRPCServerConfig {
	if in == nil {
		return nil
	}
	out := new(GRPCServerConfig)
	in.DeepCopyInto(out)
	return out
}
