# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import check_pb2 as aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2


class FlowControlServiceStub(object):
    """FlowControlService is used to perform Flow Control operations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/aperture.flowcontrol.check.v1.FlowControlService/Check',
                request_serializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CheckRequest.SerializeToString,
                response_deserializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CheckResponse.FromString,
                )
        self.CacheLookup = channel.unary_unary(
                '/aperture.flowcontrol.check.v1.FlowControlService/CacheLookup',
                request_serializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CacheLookupRequest.SerializeToString,
                response_deserializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CacheLookupResponse.FromString,
                )
        self.CacheUpsert = channel.unary_unary(
                '/aperture.flowcontrol.check.v1.FlowControlService/CacheUpsert',
                request_serializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CacheUpsertRequest.SerializeToString,
                response_deserializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CacheUpsertResponse.FromString,
                )
        self.CacheDelete = channel.unary_unary(
                '/aperture.flowcontrol.check.v1.FlowControlService/CacheDelete',
                request_serializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CacheDeleteRequest.SerializeToString,
                response_deserializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CacheDeleteResponse.FromString,
                )
        self.FlowEnd = channel.unary_unary(
                '/aperture.flowcontrol.check.v1.FlowControlService/FlowEnd',
                request_serializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.FlowEndRequest.SerializeToString,
                response_deserializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.FlowEndResponse.FromString,
                )


class FlowControlServiceServicer(object):
    """FlowControlService is used to perform Flow Control operations.
    """

    def Check(self, request, context):
        """Check wraps the given arbitrary resource and matches the given labels against Flow Control Limiters to makes a decision whether to allow/deny.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CacheLookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CacheUpsert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CacheDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FlowEnd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlowControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CheckRequest.FromString,
                    response_serializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CheckResponse.SerializeToString,
            ),
            'CacheLookup': grpc.unary_unary_rpc_method_handler(
                    servicer.CacheLookup,
                    request_deserializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CacheLookupRequest.FromString,
                    response_serializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CacheLookupResponse.SerializeToString,
            ),
            'CacheUpsert': grpc.unary_unary_rpc_method_handler(
                    servicer.CacheUpsert,
                    request_deserializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CacheUpsertRequest.FromString,
                    response_serializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CacheUpsertResponse.SerializeToString,
            ),
            'CacheDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.CacheDelete,
                    request_deserializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CacheDeleteRequest.FromString,
                    response_serializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CacheDeleteResponse.SerializeToString,
            ),
            'FlowEnd': grpc.unary_unary_rpc_method_handler(
                    servicer.FlowEnd,
                    request_deserializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.FlowEndRequest.FromString,
                    response_serializer=aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.FlowEndResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aperture.flowcontrol.check.v1.FlowControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FlowControlService(object):
    """FlowControlService is used to perform Flow Control operations.
    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aperture.flowcontrol.check.v1.FlowControlService/Check',
            aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CheckRequest.SerializeToString,
            aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CacheLookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aperture.flowcontrol.check.v1.FlowControlService/CacheLookup',
            aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CacheLookupRequest.SerializeToString,
            aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CacheLookupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CacheUpsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aperture.flowcontrol.check.v1.FlowControlService/CacheUpsert',
            aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CacheUpsertRequest.SerializeToString,
            aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CacheUpsertResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CacheDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aperture.flowcontrol.check.v1.FlowControlService/CacheDelete',
            aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CacheDeleteRequest.SerializeToString,
            aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.CacheDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FlowEnd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aperture.flowcontrol.check.v1.FlowControlService/FlowEnd',
            aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.FlowEndRequest.SerializeToString,
            aperture_dot_flowcontrol_dot_check_dot_v1_dot_check__pb2.FlowEndResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
