"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import aperture.flowcontrol.check.v1.check_pb2
import grpc
import grpc.aio
import typing

class FlowControlServiceStub:
    """FlowControlService is used to perform Flow Control operations."""

    def __init__(self, channel: grpc.Channel) -> None: ...
    Check: grpc.UnaryUnaryMultiCallable[
        aperture.flowcontrol.check.v1.check_pb2.CheckRequest,
        aperture.flowcontrol.check.v1.check_pb2.CheckResponse,
    ]
    """Check wraps the given arbitrary resource and matches the given labels against Flow Control Limiters to makes a decision whether to allow/deny."""

class FlowControlServiceServicer(metaclass=abc.ABCMeta):
    """FlowControlService is used to perform Flow Control operations."""

    @abc.abstractmethod
    def Check(
        self,
        request: aperture.flowcontrol.check.v1.check_pb2.CheckRequest,
        context: grpc.ServicerContext,
    ) -> aperture.flowcontrol.check.v1.check_pb2.CheckResponse:
        """Check wraps the given arbitrary resource and matches the given labels against Flow Control Limiters to makes a decision whether to allow/deny."""

def add_FlowControlServiceServicer_to_server(servicer: FlowControlServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
