"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class CheckRequest(google.protobuf.message.Message):
    """CheckRequest contains fields required to perform Check call."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class LabelsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    CONTROL_POINT_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    control_point: builtins.str
    @property
    def labels(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        control_point: builtins.str = ...,
        labels: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["control_point", b"control_point", "labels", b"labels"]) -> None: ...

global___CheckRequest = CheckRequest

@typing_extensions.final
class CheckResponse(google.protobuf.message.Message):
    """CheckResponse contains fields that represent decision made by Check call."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _RejectReason:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _RejectReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CheckResponse._RejectReason.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        REJECT_REASON_NONE: CheckResponse._RejectReason.ValueType  # 0
        REJECT_REASON_RATE_LIMITED: CheckResponse._RejectReason.ValueType  # 1
        REJECT_REASON_CONCURRENCY_LIMITED: CheckResponse._RejectReason.ValueType  # 2

    class RejectReason(_RejectReason, metaclass=_RejectReasonEnumTypeWrapper):
        """RejectReason contains fields that give further information about rejection."""

    REJECT_REASON_NONE: CheckResponse.RejectReason.ValueType  # 0
    REJECT_REASON_RATE_LIMITED: CheckResponse.RejectReason.ValueType  # 1
    REJECT_REASON_CONCURRENCY_LIMITED: CheckResponse.RejectReason.ValueType  # 2

    class _DecisionType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _DecisionTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CheckResponse._DecisionType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        DECISION_TYPE_ACCEPTED: CheckResponse._DecisionType.ValueType  # 0
        DECISION_TYPE_REJECTED: CheckResponse._DecisionType.ValueType  # 1

    class DecisionType(_DecisionType, metaclass=_DecisionTypeEnumTypeWrapper):
        """DecisionType contains fields that represent decision made by Check call."""

    DECISION_TYPE_ACCEPTED: CheckResponse.DecisionType.ValueType  # 0
    DECISION_TYPE_REJECTED: CheckResponse.DecisionType.ValueType  # 1

    @typing_extensions.final
    class TelemetryFlowLabelsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    SERVICES_FIELD_NUMBER: builtins.int
    CONTROL_POINT_FIELD_NUMBER: builtins.int
    FLOW_LABEL_KEYS_FIELD_NUMBER: builtins.int
    TELEMETRY_FLOW_LABELS_FIELD_NUMBER: builtins.int
    DECISION_TYPE_FIELD_NUMBER: builtins.int
    REJECT_REASON_FIELD_NUMBER: builtins.int
    CLASSIFIER_INFOS_FIELD_NUMBER: builtins.int
    FLUX_METER_INFOS_FIELD_NUMBER: builtins.int
    LIMITER_DECISIONS_FIELD_NUMBER: builtins.int
    @property
    def start(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """start timestamp"""
    @property
    def end(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """end timestamp"""
    @property
    def services(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """services that matched"""
    control_point: builtins.str
    """control_point of request"""
    @property
    def flow_label_keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """flow label keys that were matched for this request."""
    @property
    def telemetry_flow_labels(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """telemetry_flow_labels are labels for telemetry purpose. The keys in telemetry_flow_labels is subset of flow_label_keys."""
    decision_type: global___CheckResponse.DecisionType.ValueType
    """decision_type contains what the decision was."""
    reject_reason: global___CheckResponse.RejectReason.ValueType
    """reject_reason contains the reason for the rejection."""
    @property
    def classifier_infos(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ClassifierInfo]:
        """classifiers that were matched for this request."""
    @property
    def flux_meter_infos(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FluxMeterInfo]:
        """flux meters that were matched for this request."""
    @property
    def limiter_decisions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LimiterDecision]:
        """limiter_decisions contains information about decision made by each limiter."""
    def __init__(
        self,
        *,
        start: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        services: collections.abc.Iterable[builtins.str] | None = ...,
        control_point: builtins.str = ...,
        flow_label_keys: collections.abc.Iterable[builtins.str] | None = ...,
        telemetry_flow_labels: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        decision_type: global___CheckResponse.DecisionType.ValueType = ...,
        reject_reason: global___CheckResponse.RejectReason.ValueType = ...,
        classifier_infos: collections.abc.Iterable[global___ClassifierInfo] | None = ...,
        flux_meter_infos: collections.abc.Iterable[global___FluxMeterInfo] | None = ...,
        limiter_decisions: collections.abc.Iterable[global___LimiterDecision] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["end", b"end", "start", b"start"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["classifier_infos", b"classifier_infos", "control_point", b"control_point", "decision_type", b"decision_type", "end", b"end", "flow_label_keys", b"flow_label_keys", "flux_meter_infos", b"flux_meter_infos", "limiter_decisions", b"limiter_decisions", "reject_reason", b"reject_reason", "services", b"services", "start", b"start", "telemetry_flow_labels", b"telemetry_flow_labels"]) -> None: ...

global___CheckResponse = CheckResponse

@typing_extensions.final
class ClassifierInfo(google.protobuf.message.Message):
    """ClassifierInfo describes details for each ClassifierInfo."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Error:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ClassifierInfo._Error.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        ERROR_NONE: ClassifierInfo._Error.ValueType  # 0
        ERROR_EVAL_FAILED: ClassifierInfo._Error.ValueType  # 1
        ERROR_EMPTY_RESULTSET: ClassifierInfo._Error.ValueType  # 2
        ERROR_AMBIGUOUS_RESULTSET: ClassifierInfo._Error.ValueType  # 3
        ERROR_MULTI_EXPRESSION: ClassifierInfo._Error.ValueType  # 4
        ERROR_EXPRESSION_NOT_MAP: ClassifierInfo._Error.ValueType  # 5

    class Error(_Error, metaclass=_ErrorEnumTypeWrapper):
        """Error information."""

    ERROR_NONE: ClassifierInfo.Error.ValueType  # 0
    ERROR_EVAL_FAILED: ClassifierInfo.Error.ValueType  # 1
    ERROR_EMPTY_RESULTSET: ClassifierInfo.Error.ValueType  # 2
    ERROR_AMBIGUOUS_RESULTSET: ClassifierInfo.Error.ValueType  # 3
    ERROR_MULTI_EXPRESSION: ClassifierInfo.Error.ValueType  # 4
    ERROR_EXPRESSION_NOT_MAP: ClassifierInfo.Error.ValueType  # 5

    POLICY_NAME_FIELD_NUMBER: builtins.int
    POLICY_HASH_FIELD_NUMBER: builtins.int
    CLASSIFIER_INDEX_FIELD_NUMBER: builtins.int
    LABEL_KEY_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    policy_name: builtins.str
    policy_hash: builtins.str
    classifier_index: builtins.int
    label_key: builtins.str
    error: global___ClassifierInfo.Error.ValueType
    def __init__(
        self,
        *,
        policy_name: builtins.str = ...,
        policy_hash: builtins.str = ...,
        classifier_index: builtins.int = ...,
        label_key: builtins.str = ...,
        error: global___ClassifierInfo.Error.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["classifier_index", b"classifier_index", "error", b"error", "label_key", b"label_key", "policy_hash", b"policy_hash", "policy_name", b"policy_name"]) -> None: ...

global___ClassifierInfo = ClassifierInfo

@typing_extensions.final
class LimiterDecision(google.protobuf.message.Message):
    """LimiterDecision describes details for each limiter."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _LimiterReason:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _LimiterReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[LimiterDecision._LimiterReason.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        LIMITER_REASON_UNSPECIFIED: LimiterDecision._LimiterReason.ValueType  # 0
        LIMITER_REASON_KEY_NOT_FOUND: LimiterDecision._LimiterReason.ValueType  # 1

    class LimiterReason(_LimiterReason, metaclass=_LimiterReasonEnumTypeWrapper): ...
    LIMITER_REASON_UNSPECIFIED: LimiterDecision.LimiterReason.ValueType  # 0
    LIMITER_REASON_KEY_NOT_FOUND: LimiterDecision.LimiterReason.ValueType  # 1

    @typing_extensions.final
    class RateLimiterInfo(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        REMAINING_FIELD_NUMBER: builtins.int
        CURRENT_FIELD_NUMBER: builtins.int
        LABEL_FIELD_NUMBER: builtins.int
        remaining: builtins.int
        current: builtins.int
        label: builtins.str
        def __init__(
            self,
            *,
            remaining: builtins.int = ...,
            current: builtins.int = ...,
            label: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["current", b"current", "label", b"label", "remaining", b"remaining"]) -> None: ...

    @typing_extensions.final
    class ConcurrencyLimiterInfo(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        WORKLOAD_INDEX_FIELD_NUMBER: builtins.int
        workload_index: builtins.str
        def __init__(
            self,
            *,
            workload_index: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["workload_index", b"workload_index"]) -> None: ...

    POLICY_NAME_FIELD_NUMBER: builtins.int
    POLICY_HASH_FIELD_NUMBER: builtins.int
    COMPONENT_ID_FIELD_NUMBER: builtins.int
    DROPPED_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    RATE_LIMITER_INFO_FIELD_NUMBER: builtins.int
    CONCURRENCY_LIMITER_INFO_FIELD_NUMBER: builtins.int
    policy_name: builtins.str
    policy_hash: builtins.str
    component_id: builtins.str
    dropped: builtins.bool
    reason: global___LimiterDecision.LimiterReason.ValueType
    @property
    def rate_limiter_info(self) -> global___LimiterDecision.RateLimiterInfo: ...
    @property
    def concurrency_limiter_info(self) -> global___LimiterDecision.ConcurrencyLimiterInfo: ...
    def __init__(
        self,
        *,
        policy_name: builtins.str = ...,
        policy_hash: builtins.str = ...,
        component_id: builtins.str = ...,
        dropped: builtins.bool = ...,
        reason: global___LimiterDecision.LimiterReason.ValueType = ...,
        rate_limiter_info: global___LimiterDecision.RateLimiterInfo | None = ...,
        concurrency_limiter_info: global___LimiterDecision.ConcurrencyLimiterInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["concurrency_limiter_info", b"concurrency_limiter_info", "details", b"details", "rate_limiter_info", b"rate_limiter_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["component_id", b"component_id", "concurrency_limiter_info", b"concurrency_limiter_info", "details", b"details", "dropped", b"dropped", "policy_hash", b"policy_hash", "policy_name", b"policy_name", "rate_limiter_info", b"rate_limiter_info", "reason", b"reason"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["details", b"details"]) -> typing_extensions.Literal["rate_limiter_info", "concurrency_limiter_info"] | None: ...

global___LimiterDecision = LimiterDecision

@typing_extensions.final
class FluxMeterInfo(google.protobuf.message.Message):
    """FluxMeterInfo describes detail for each FluxMeterInfo."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FLUX_METER_NAME_FIELD_NUMBER: builtins.int
    flux_meter_name: builtins.str
    def __init__(
        self,
        *,
        flux_meter_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["flux_meter_name", b"flux_meter_name"]) -> None: ...

global___FluxMeterInfo = FluxMeterInfo
