//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package config

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchAlertsConfig) DeepCopyInto(out *BatchAlertsConfig) {
	*out = *in
	in.Timeout.DeepCopyInto(&out.Timeout)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchAlertsConfig.
func (in *BatchAlertsConfig) DeepCopy() *BatchAlertsConfig {
	if in == nil {
		return nil
	}
	out := new(BatchAlertsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchPostrollupConfig) DeepCopyInto(out *BatchPostrollupConfig) {
	*out = *in
	in.Timeout.DeepCopyInto(&out.Timeout)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchPostrollupConfig.
func (in *BatchPostrollupConfig) DeepCopy() *BatchPostrollupConfig {
	if in == nil {
		return nil
	}
	out := new(BatchPostrollupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchPrerollupConfig) DeepCopyInto(out *BatchPrerollupConfig) {
	*out = *in
	in.Timeout.DeepCopyInto(&out.Timeout)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchPrerollupConfig.
func (in *BatchPrerollupConfig) DeepCopy() *BatchPrerollupConfig {
	if in == nil {
		return nil
	}
	out := new(BatchPrerollupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortsConfig) DeepCopyInto(out *PortsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortsConfig.
func (in *PortsConfig) DeepCopy() *PortsConfig {
	if in == nil {
		return nil
	}
	out := new(PortsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserOTELConfig) DeepCopyInto(out *UserOTELConfig) {
	*out = *in
	in.BatchPrerollup.DeepCopyInto(&out.BatchPrerollup)
	in.BatchPostrollup.DeepCopyInto(&out.BatchPostrollup)
	in.BatchAlerts.DeepCopyInto(&out.BatchAlerts)
	out.Ports = in.Ports
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserOTELConfig.
func (in *UserOTELConfig) DeepCopy() *UserOTELConfig {
	if in == nil {
		return nil
	}
	out := new(UserOTELConfig)
	in.DeepCopyInto(out)
	return out
}
