flowchart LR
subgraph root.0[<center>PromQL<br/>every 1s</center>]
subgraph root.0_outports[ ]
style root.0_outports fill:none,stroke:none
root.0output[output]
end
end
subgraph root.1[<center>ArithmeticCombinator<br/>Mul</center>]
subgraph root.1_inports[ ]
style root.1_inports fill:none,stroke:none
root.1lhs[lhs]
root.1rhs[rhs]
end
subgraph root.1_outports[ ]
style root.1_outports fill:none,stroke:none
root.1output[output]
end
end
root.1_rhs_FakeConstantout((2.00))
subgraph root.2[<center>ArithmeticCombinator<br/>Mul</center>]
subgraph root.2_inports[ ]
style root.2_inports fill:none,stroke:none
root.2lhs[lhs]
root.2rhs[rhs]
end
subgraph root.2_outports[ ]
style root.2_outports fill:none,stroke:none
root.2output[output]
end
end
root.2_rhs_FakeConstantout((1.10))
subgraph root.3[<center>EMA<br/>win: 3000</center>]
subgraph root.3_inports[ ]
style root.3_inports fill:none,stroke:none
root.3input[input]
root.3max_envelope[max_envelope]
end
subgraph root.3_outports[ ]
style root.3_outports fill:none,stroke:none
root.3output[output]
end
end
subgraph root.4[<center>AdaptiveLoadScheduler<br/>1 selectors</center>]
subgraph root.4_inports[ ]
style root.4_inports fill:none,stroke:none
root.4setpoint[setpoint]
root.4signal[signal]
end
subgraph root.4_outports[ ]
style root.4_outports fill:none,stroke:none
root.4observed_load_multiplier[observed_load_multiplier]
end
end
subgraph root.5[<center>PromQL<br/>every 10s</center>]
subgraph root.5_outports[ ]
style root.5_outports fill:none,stroke:none
root.5output[output]
end
end
subgraph root.6[<center>AutoScaler<br/>demoapp:Deployment/service1...</center>]
subgraph root.6_inports[ ]
style root.6_inports fill:none,stroke:none
root.6scale_in_setpoint_0[scale_in_setpoint_0]
root.6scale_in_signal_0[scale_in_signal_0]
root.6scale_out_setpoint_0[scale_out_setpoint_0]
root.6scale_out_signal_0[scale_out_signal_0]
end
end
root.6_scale_in_setpoint_0_FakeConstantout((0.50))
root.6_scale_out_setpoint_0_FakeConstantout((1.00))
root.0output --> |LATENCY| root.1lhs
root.0output --> |LATENCY| root.3input
root.0output --> |LATENCY| root.4signal
root.1output --> |MAX_EMA| root.3max_envelope
root.1_rhs_FakeConstantout --> root.1rhs
root.2output --> |LATENCY_SETPOINT| root.4setpoint
root.2_rhs_FakeConstantout --> root.2rhs
root.3output --> |LATENCY_EMA| root.2lhs
root.4observed_load_multiplier --> |OBSERVED_LOAD_MULTIPLIER| root.6scale_out_signal_0
root.5output --> |AVERAGE_CPU| root.6scale_in_signal_0
root.6_scale_in_setpoint_0_FakeConstantout --> root.6scale_in_setpoint_0
root.6_scale_out_setpoint_0_FakeConstantout --> root.6scale_out_setpoint_0
