flowchart TD
classDef TokenBucket fill:#F8773D, stroke:#000000,stroke-width:2px;
classDef Service fill:#56AE89,stroke:#000000,stroke-width:2px;


Forward("Aperture Cloud") --> TB
class Forward Service

TB[\Token Bucket/]
class TB TokenBucket

SDK
class SDK Service
TB <-- "Counting" --> SDK
