flowchart LR
classDef TokenBucket fill:#F8773D,stroke:#000000,stroke-width:2px;
classDef Service fill:#56AE89,stroke:#000000,stroke-width:2px;

subgraph Cloud
TB[\Token Bucket/]
class TB TokenBucket
end
class Cloud Service

TB <-- "counting tokens" --> SDK

  subgraph "SDK"
  end
  class SDK Service