//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package http

import (
	nethttpx "net/http"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPClientConfig) DeepCopyInto(out *HTTPClientConfig) {
	*out = *in
	in.NetworkKeepAlive.DeepCopyInto(&out.NetworkKeepAlive)
	in.NetworkTimeout.DeepCopyInto(&out.NetworkTimeout)
	in.Timeout.DeepCopyInto(&out.Timeout)
	if in.ProxyConnectHeader != nil {
		in, out := &in.ProxyConnectHeader, &out.ProxyConnectHeader
		*out = make(nethttpx.Header, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	in.TLSHandshakeTimeout.DeepCopyInto(&out.TLSHandshakeTimeout)
	in.ExpectContinueTimeout.DeepCopyInto(&out.ExpectContinueTimeout)
	in.ResponseHeaderTimeout.DeepCopyInto(&out.ResponseHeaderTimeout)
	in.IdleConnTimeout.DeepCopyInto(&out.IdleConnTimeout)
	out.ClientTLSConfig = in.ClientTLSConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPClientConfig.
func (in *HTTPClientConfig) DeepCopy() *HTTPClientConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPServerConfig) DeepCopyInto(out *HTTPServerConfig) {
	*out = *in
	in.IdleTimeout.DeepCopyInto(&out.IdleTimeout)
	in.ReadHeaderTimeout.DeepCopyInto(&out.ReadHeaderTimeout)
	in.ReadTimeout.DeepCopyInto(&out.ReadTimeout)
	in.WriteTimeout.DeepCopyInto(&out.WriteTimeout)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPServerConfig.
func (in *HTTPServerConfig) DeepCopy() *HTTPServerConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyConfig) DeepCopyInto(out *ProxyConfig) {
	*out = *in
	if in.NoProxy != nil {
		in, out := &in.NoProxy, &out.NoProxy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyConfig.
func (in *ProxyConfig) DeepCopy() *ProxyConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyConfig)
	in.DeepCopyInto(out)
	return out
}
