flowchart LR
subgraph root.0[PromQL]
subgraph root.0_outports[ ]
style root.0_outports fill:none,stroke:none
root.0output[output]
end
end
subgraph root.1[<center>ArithmeticCombinator<br/>mul</center>]
subgraph root.1_inports[ ]
style root.1_inports fill:none,stroke:none
root.1lhs[lhs]
root.1rhs[rhs]
end
subgraph root.1_outports[ ]
style root.1_outports fill:none,stroke:none
root.1output[output]
end
end
FakeConstant0((2.00))
FakeConstant0 --> root.1rhs
subgraph root.2[<center>ArithmeticCombinator<br/>mul</center>]
subgraph root.2_inports[ ]
style root.2_inports fill:none,stroke:none
root.2rhs[rhs]
root.2lhs[lhs]
end
subgraph root.2_outports[ ]
style root.2_outports fill:none,stroke:none
root.2output[output]
end
end
FakeConstant1((1.10))
FakeConstant1 --> root.2rhs
subgraph root.3[<center>EMA<br/>win: 1500s</center>]
subgraph root.3_inports[ ]
style root.3_inports fill:none,stroke:none
root.3input[input]
root.3max_envelope[max_envelope]
end
subgraph root.3_outports[ ]
style root.3_outports fill:none,stroke:none
root.3output[output]
end
end
subgraph root.4.0[<center>ArithmeticCombinator<br/>div</center>]
subgraph root.4.0_inports[ ]
style root.4.0_inports fill:none,stroke:none
root.4.0lhs[lhs]
root.4.0rhs[rhs]
end
subgraph root.4.0_outports[ ]
style root.4.0_outports fill:none,stroke:none
root.4.0output[output]
end
end
subgraph root.4.1[<center>ArithmeticCombinator<br/>mul</center>]
subgraph root.4.1_inports[ ]
style root.4.1_inports fill:none,stroke:none
root.4.1lhs[lhs]
root.4.1rhs[rhs]
end
subgraph root.4.1_outports[ ]
style root.4.1_outports fill:none,stroke:none
root.4.1output[output]
end
end
FakeConstant2((2.00))
FakeConstant2 --> root.4.1lhs
subgraph root.4.2[<center>ArithmeticCombinator<br/>add</center>]
subgraph root.4.2_inports[ ]
style root.4.2_inports fill:none,stroke:none
root.4.2lhs[lhs]
root.4.2rhs[rhs]
end
subgraph root.4.2_outports[ ]
style root.4.2_outports fill:none,stroke:none
root.4.2output[output]
end
end
FakeConstant3((5.00))
FakeConstant3 --> root.4.2lhs
subgraph root.4.3[<center>ArithmeticCombinator<br/>add</center>]
subgraph root.4.3_inports[ ]
style root.4.3_inports fill:none,stroke:none
root.4.3lhs[lhs]
root.4.3rhs[rhs]
end
subgraph root.4.3_outports[ ]
style root.4.3_outports fill:none,stroke:none
root.4.3output[output]
end
end
subgraph root.4.4[Min]
subgraph root.4.4_inports[ ]
style root.4.4_inports fill:none,stroke:none
root.4.4inputs[inputs]
root.4.4inputs[inputs]
end
subgraph root.4.4_outports[ ]
style root.4.4_outports fill:none,stroke:none
root.4.4output[output]
end
end
subgraph root.4.5[FirstValid]
subgraph root.4.5_inports[ ]
style root.4.5_inports fill:none,stroke:none
root.4.5inputs[inputs]
root.4.5inputs[inputs]
end
subgraph root.4.5_outports[ ]
style root.4.5_outports fill:none,stroke:none
root.4.5output[output]
end
end
FakeConstant4((0.00))
FakeConstant4 --> root.4.5inputs
subgraph root.4.6[Sqrt]
subgraph root.4.6_inports[ ]
style root.4.6_inports fill:none,stroke:none
root.4.6input[input]
end
subgraph root.4.6_outports[ ]
style root.4.6_outports fill:none,stroke:none
root.4.6output[output]
end
end
subgraph root.4.7[Gradient]
subgraph root.4.7_inports[ ]
style root.4.7_inports fill:none,stroke:none
root.4.7setpoint[setpoint]
root.4.7optimize[optimize]
root.4.7max[max]
root.4.7control_variable[control_variable]
root.4.7signal[signal]
end
subgraph root.4.7_outports[ ]
style root.4.7_outports fill:none,stroke:none
root.4.7output[output]
end
end
subgraph root.4.8[<center>Extrapolator<br/>for: 5s</center>]
subgraph root.4.8_inports[ ]
style root.4.8_inports fill:none,stroke:none
root.4.8input[input]
end
subgraph root.4.8_outports[ ]
style root.4.8_outports fill:none,stroke:none
root.4.8output[output]
end
end
subgraph root.4.9.Scheduler[Scheduler]
subgraph root.4.9.Scheduler_outports[ ]
style root.4.9.Scheduler_outports fill:none,stroke:none
root.4.9.Scheduleraccepted_concurrency[accepted_concurrency]
root.4.9.Schedulerincoming_concurrency[incoming_concurrency]
end
end
subgraph root.4.9.LoadActuator[LoadActuator]
subgraph root.4.9.LoadActuator_inports[ ]
style root.4.9.LoadActuator_inports fill:none,stroke:none
root.4.9.LoadActuatorload_multiplier[load_multiplier]
end
end
subgraph root.4.10[<center>Decider<br/>gt for 0s</center>]
subgraph root.4.10_inports[ ]
style root.4.10_inports fill:none,stroke:none
root.4.10lhs[lhs]
root.4.10rhs[rhs]
end
subgraph root.4.10_outports[ ]
style root.4.10_outports fill:none,stroke:none
root.4.10output[output]
end
end
subgraph root.4.11[Switcher]
subgraph root.4.11_inports[ ]
style root.4.11_inports fill:none,stroke:none
root.4.11on_true[on_true]
root.4.11on_false[on_false]
root.4.11switch[switch]
end
subgraph root.4.11_outports[ ]
style root.4.11_outports fill:none,stroke:none
root.4.11output[output]
end
end
FakeConstant5((0.00))
FakeConstant5 --> root.4.11on_true
subgraph root.4.12[NestedSignalIngress]
subgraph root.4.12_inports[ ]
style root.4.12_inports fill:none,stroke:none
root.4.12signal[signal]
end
subgraph root.4.12_outports[ ]
style root.4.12_outports fill:none,stroke:none
root.4.12signal[signal]
end
end
subgraph root.4.13[NestedSignalIngress]
subgraph root.4.13_inports[ ]
style root.4.13_inports fill:none,stroke:none
root.4.13signal[signal]
end
subgraph root.4.13_outports[ ]
style root.4.13_outports fill:none,stroke:none
root.4.13signal[signal]
end
end
subgraph root.4.14[NestedSignalEgress]
subgraph root.4.14_inports[ ]
style root.4.14_inports fill:none,stroke:none
root.4.14signal[signal]
end
subgraph root.4.14_outports[ ]
style root.4.14_outports fill:none,stroke:none
root.4.14signal[signal]
end
end
subgraph root.4.15[NestedSignalEgress]
subgraph root.4.15_inports[ ]
style root.4.15_inports fill:none,stroke:none
root.4.15signal[signal]
end
subgraph root.4.15_outports[ ]
style root.4.15_outports fill:none,stroke:none
root.4.15signal[signal]
end
end
subgraph root.4.16[NestedSignalEgress]
subgraph root.4.16_inports[ ]
style root.4.16_inports fill:none,stroke:none
root.4.16signal[signal]
end
subgraph root.4.16_outports[ ]
style root.4.16_outports fill:none,stroke:none
root.4.16signal[signal]
end
end
subgraph root.4.17[NestedSignalEgress]
subgraph root.4.17_inports[ ]
style root.4.17_inports fill:none,stroke:none
root.4.17signal[signal]
end
subgraph root.4.17_outports[ ]
style root.4.17_outports fill:none,stroke:none
root.4.17signal[signal]
end
end
subgraph root.4.18[NestedSignalEgress]
subgraph root.4.18_inports[ ]
style root.4.18_inports fill:none,stroke:none
root.4.18signal[signal]
end
subgraph root.4.18_outports[ ]
style root.4.18_outports fill:none,stroke:none
root.4.18signal[signal]
end
end
root.1output --> |MAX_EMA| root.3max_envelope
root.4.4output --> |CONCURRENCY_INCREMENT_INTEGRAL_CAPPED| root.4.5inputs
root.4.13signal --> |SETPOINT| root.4.7setpoint
root.4.13signal --> |SETPOINT| root.4.10rhs
root.3output --> |LATENCY_EMA| root.2lhs
root.4.0output --> |DESIRED_CONCURRENCY_RATIO| root.4.8input
root.4.5output --> |CONCURRENCY_INCREMENT_NORMAL| root.4.11on_false
root.4.6output --> |SQRT_CONCURRENCY_INCREMENT| root.4.2rhs
root.4.8output --> |LOAD_MULTIPLIER| root.4.9.LoadActuatorload_multiplier
root.4.8output --> |LOAD_MULTIPLIER| root.4.18signal
root.4.18signal --> |LOAD_MULTIPLIER| root.4.9.LoadActuatorload_multiplier
root.4.18signal --> |LOAD_MULTIPLIER| root.4.18signal
root.4.9.Scheduleraccepted_concurrency --> |ACCEPTED_CONCURRENCY| root.4.1rhs
root.4.9.Scheduleraccepted_concurrency --> |ACCEPTED_CONCURRENCY| root.4.4inputs
root.4.9.Scheduleraccepted_concurrency --> |ACCEPTED_CONCURRENCY| root.4.6input
root.4.9.Scheduleraccepted_concurrency --> |ACCEPTED_CONCURRENCY| root.4.7control_variable
root.4.9.Scheduleraccepted_concurrency --> |ACCEPTED_CONCURRENCY| root.4.14signal
root.4.14signal --> |ACCEPTED_CONCURRENCY| root.4.1rhs
root.4.14signal --> |ACCEPTED_CONCURRENCY| root.4.4inputs
root.4.14signal --> |ACCEPTED_CONCURRENCY| root.4.6input
root.4.14signal --> |ACCEPTED_CONCURRENCY| root.4.7control_variable
root.4.14signal --> |ACCEPTED_CONCURRENCY| root.4.14signal
root.4.10output --> |IS_OVERLOAD| root.4.11switch
root.4.10output --> |IS_OVERLOAD| root.4.17signal
root.4.17signal --> |IS_OVERLOAD| root.4.11switch
root.4.17signal --> |IS_OVERLOAD| root.4.17signal
root.0output --> |LATENCY| root.1lhs
root.0output --> |LATENCY| root.3input
root.0output --> |LATENCY| root.4.12signal
root.4.2output --> |CONCURRENCY_INCREMENT_SINGLE_TICK| root.4.3lhs
root.4.7output --> |DESIRED_CONCURRENCY| root.4.0lhs
root.4.7output --> |DESIRED_CONCURRENCY| root.4.16signal
root.4.16signal --> |DESIRED_CONCURRENCY| root.4.0lhs
root.4.16signal --> |DESIRED_CONCURRENCY| root.4.16signal
root.4.9.Schedulerincoming_concurrency --> |INCOMING_CONCURRENCY| root.4.0rhs
root.4.9.Schedulerincoming_concurrency --> |INCOMING_CONCURRENCY| root.4.15signal
root.4.15signal --> |INCOMING_CONCURRENCY| root.4.0rhs
root.4.15signal --> |INCOMING_CONCURRENCY| root.4.15signal
root.4.12signal --> |SIGNAL| root.4.7signal
root.4.12signal --> |SIGNAL| root.4.10lhs
root.2output --> |LATENCY_SETPOINT| root.4.13signal
root.4.1output --> |NORMAL_CONCURRENCY_LIMIT| root.4.7max
root.4.3output --> |CONCURRENCY_INCREMENT_INTEGRAL| root.4.4inputs
root.4.11output --> |CONCURRENCY_INCREMENT| root.4.3rhs
root.4.11output --> |CONCURRENCY_INCREMENT| root.4.7optimize
