flowchart LR
subgraph 0[<center>RateLimiter<br/>service1-demo-ap...</center>]
subgraph 0_inports[ ]
style 0_inports fill:none,stroke:none
0limit[limit]
end
end
FakeConstant0((120.00))
FakeConstant0 --> 0limit
