// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text string `json:"text"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
