flowchart LR
subgraph root.0[<center>PromQL<br/>every 1s</center>]
subgraph root.0_outports[ ]
style root.0_outports fill:none,stroke:none
end
end
FakeConstant0((2.00))
FakeConstant0 --> root.1rhs
subgraph root.1[<center>ArithmeticCombinator<br/>Mul</center>]
subgraph root.1_inports[ ]
style root.1_inports fill:none,stroke:none
root.1rhs[rhs]
end
subgraph root.1_outports[ ]
style root.1_outports fill:none,stroke:none
end
end
FakeConstant1((1.10))
FakeConstant1 --> root.2rhs
subgraph root.2[<center>ArithmeticCombinator<br/>Mul</center>]
subgraph root.2_inports[ ]
style root.2_inports fill:none,stroke:none
root.2rhs[rhs]
end
subgraph root.2_outports[ ]
style root.2_outports fill:none,stroke:none
end
end
subgraph root.3[<center>EMA<br/>win: 3000</center>]
subgraph root.3_inports[ ]
style root.3_inports fill:none,stroke:none
end
subgraph root.3_outports[ ]
style root.3_outports fill:none,stroke:none
end
end
subgraph root.4.0[<center>ArithmeticCombinator<br/>Div</center>]
subgraph root.4.0_inports[ ]
style root.4.0_inports fill:none,stroke:none
end
subgraph root.4.0_outports[ ]
style root.4.0_outports fill:none,stroke:none
end
end
FakeConstant2((2.00))
FakeConstant2 --> root.4.1max
subgraph root.4.1[<center>GradientController<br/>slope: -1, min: 0.1, max: 1</center>]
subgraph root.4.1_inports[ ]
style root.4.1_inports fill:none,stroke:none
root.4.1max[max]
end
subgraph root.4.1_outports[ ]
style root.4.1_outports fill:none,stroke:none
end
end
subgraph root.4.2[<center>Extrapolator<br/>for: 5s</center>]
subgraph root.4.2_inports[ ]
style root.4.2_inports fill:none,stroke:none
end
subgraph root.4.2_outports[ ]
style root.4.2_outports fill:none,stroke:none
end
end
subgraph root.4.3.Scheduler[<center>Scheduler<br/>default</center>]
subgraph root.4.3.Scheduler_outports[ ]
style root.4.3.Scheduler_outports fill:none,stroke:none
end
end
subgraph root.4.3..LoadActuator[<center>LoadActuator<br/>default</center>]
subgraph root.4.3..LoadActuator_inports[ ]
style root.4.3..LoadActuator_inports fill:none,stroke:none
end
end
FakeConstant3((1.00))
FakeConstant3 --> root.4.4rhs
subgraph root.4.4[<center>Decider<br/>LT for 0s</center>]
subgraph root.4.4_inports[ ]
style root.4.4_inports fill:none,stroke:none
root.4.4rhs[rhs]
end
subgraph root.4.4_outports[ ]
style root.4.4_outports fill:none,stroke:none
end
end
subgraph root.4.5[<center>Alerter<br/>Load Shed Event/info</center>]
subgraph root.4.5_inports[ ]
style root.4.5_inports fill:none,stroke:none
end
end
subgraph root.4.6[<center>Decider<br/>GT for 0s</center>]
subgraph root.4.6_inports[ ]
style root.4.6_inports fill:none,stroke:none
end
subgraph root.4.6_outports[ ]
style root.4.6_outports fill:none,stroke:none
end
end
FakeConstant4((2.00))
FakeConstant4 --> root.4.7max
FakeConstant5((0.00))
FakeConstant5 --> root.4.7input
subgraph root.4.7[Integrator]
subgraph root.4.7_inports[ ]
style root.4.7_inports fill:none,stroke:none
root.4.7max[max]
root.4.7input[input]
end
subgraph root.4.7_outports[ ]
style root.4.7_outports fill:none,stroke:none
end
end
subgraph root.4.8[NestedSignalIngress]
subgraph root.4.8_outports[ ]
style root.4.8_outports fill:none,stroke:none
end
end
subgraph root.4.9[NestedSignalIngress]
subgraph root.4.9_outports[ ]
style root.4.9_outports fill:none,stroke:none
end
end
subgraph root.4.10[NestedSignalEgress]
subgraph root.4.10_inports[ ]
style root.4.10_inports fill:none,stroke:none
end
end
subgraph root.4.11[NestedSignalEgress]
subgraph root.4.11_inports[ ]
style root.4.11_inports fill:none,stroke:none
end
end
subgraph root.4.12[NestedSignalEgress]
subgraph root.4.12_inports[ ]
style root.4.12_inports fill:none,stroke:none
end
end
subgraph root.4.13[NestedSignalEgress]
subgraph root.4.13_inports[ ]
style root.4.13_inports fill:none,stroke:none
end
end
subgraph root.4.14[NestedSignalEgress]
subgraph root.4.14_inports[ ]
style root.4.14_inports fill:none,stroke:none
end
end
subgraph root.5[<center>PromQL<br/>every 10s</center>]
subgraph root.5_outports[ ]
style root.5_outports fill:none,stroke:none
end
end
FakeConstant6((0.01))
FakeConstant6 --> root.6.0lhs
subgraph root.6.0[<center>ArithmeticCombinator<br/>Mul</center>]
subgraph root.6.0_inports[ ]
style root.6.0_inports fill:none,stroke:none
root.6.0lhs[lhs]
end
subgraph root.6.0_outports[ ]
style root.6.0_outports fill:none,stroke:none
end
end
subgraph root.6.1[<center>UnaryOperator<br/>Floor</center>]
subgraph root.6.1_inports[ ]
style root.6.1_inports fill:none,stroke:none
end
subgraph root.6.1_outports[ ]
style root.6.1_outports fill:none,stroke:none
end
end
FakeConstant7((1.00))
FakeConstant7 --> root.6.2inputs
subgraph root.6.2[Max]
subgraph root.6.2_inports[ ]
style root.6.2_inports fill:none,stroke:none
root.6.2inputs[inputs]
end
subgraph root.6.2_outports[ ]
style root.6.2_outports fill:none,stroke:none
end
end
subgraph root.6.3[<center>ArithmeticCombinator<br/>Sub</center>]
subgraph root.6.3_inports[ ]
style root.6.3_inports fill:none,stroke:none
end
subgraph root.6.3_outports[ ]
style root.6.3_outports fill:none,stroke:none
end
end
FakeConstant8((1.00))
FakeConstant8 --> root.6.4inputs
subgraph root.6.4[Max]
subgraph root.6.4_inports[ ]
style root.6.4_inports fill:none,stroke:none
root.6.4inputs[inputs]
end
subgraph root.6.4_outports[ ]
style root.6.4_outports fill:none,stroke:none
end
end
FakeConstant9((10.00))
FakeConstant9 --> root.6.5inputs
subgraph root.6.5[Min]
subgraph root.6.5_inports[ ]
style root.6.5_inports fill:none,stroke:none
root.6.5inputs[inputs]
end
subgraph root.6.5_outports[ ]
style root.6.5_outports fill:none,stroke:none
end
end
FakeConstant10((0.10))
FakeConstant10 --> root.6.6lhs
subgraph root.6.6[<center>ArithmeticCombinator<br/>Mul</center>]
subgraph root.6.6_inports[ ]
style root.6.6_inports fill:none,stroke:none
root.6.6lhs[lhs]
end
subgraph root.6.6_outports[ ]
style root.6.6_outports fill:none,stroke:none
end
end
subgraph root.6.7[<center>UnaryOperator<br/>Floor</center>]
subgraph root.6.7_inports[ ]
style root.6.7_inports fill:none,stroke:none
end
subgraph root.6.7_outports[ ]
style root.6.7_outports fill:none,stroke:none
end
end
FakeConstant11((1.00))
FakeConstant11 --> root.6.8inputs
subgraph root.6.8[Max]
subgraph root.6.8_inports[ ]
style root.6.8_inports fill:none,stroke:none
root.6.8inputs[inputs]
end
subgraph root.6.8_outports[ ]
style root.6.8_outports fill:none,stroke:none
end
end
subgraph root.6.9[<center>ArithmeticCombinator<br/>Add</center>]
subgraph root.6.9_inports[ ]
style root.6.9_inports fill:none,stroke:none
end
subgraph root.6.9_outports[ ]
style root.6.9_outports fill:none,stroke:none
end
end
FakeConstant12((10.00))
FakeConstant12 --> root.6.10inputs
subgraph root.6.10[Min]
subgraph root.6.10_inports[ ]
style root.6.10_inports fill:none,stroke:none
root.6.10inputs[inputs]
end
subgraph root.6.10_outports[ ]
style root.6.10_outports fill:none,stroke:none
end
end
FakeConstant13((1.00))
FakeConstant13 --> root.6.11inputs
subgraph root.6.11[Max]
subgraph root.6.11_inports[ ]
style root.6.11_inports fill:none,stroke:none
root.6.11inputs[inputs]
end
subgraph root.6.11_outports[ ]
style root.6.11_outports fill:none,stroke:none
end
end
subgraph root.6.12[NestedSignalIngress]
subgraph root.6.12_outports[ ]
style root.6.12_outports fill:none,stroke:none
end
end
subgraph root.6.13[NestedSignalIngress]
subgraph root.6.13_outports[ ]
style root.6.13_outports fill:none,stroke:none
end
end
subgraph root.6.14[<center>GradientController<br/>slope: 1, min: -1.797693134...</center>]
subgraph root.6.14_inports[ ]
style root.6.14_inports fill:none,stroke:none
end
subgraph root.6.14_outports[ ]
style root.6.14_outports fill:none,stroke:none
end
end
subgraph root.6.15[<center>UnaryOperator<br/>Ceil</center>]
subgraph root.6.15_inports[ ]
style root.6.15_inports fill:none,stroke:none
end
subgraph root.6.15_outports[ ]
style root.6.15_outports fill:none,stroke:none
end
end
subgraph root.6.16[<center>Decider<br/>LT for 0s</center>]
subgraph root.6.16_inports[ ]
style root.6.16_inports fill:none,stroke:none
end
subgraph root.6.16_outports[ ]
style root.6.16_outports fill:none,stroke:none
end
end
subgraph root.6.17[Switcher]
subgraph root.6.17_inports[ ]
style root.6.17_inports fill:none,stroke:none
end
subgraph root.6.17_outports[ ]
style root.6.17_outports fill:none,stroke:none
end
end
subgraph root.6.18[NestedSignalIngress]
subgraph root.6.18_outports[ ]
style root.6.18_outports fill:none,stroke:none
end
end
subgraph root.6.19[NestedSignalIngress]
subgraph root.6.19_outports[ ]
style root.6.19_outports fill:none,stroke:none
end
end
subgraph root.6.20[<center>GradientController<br/>slope: -1, min: 1, max: 1.7...</center>]
subgraph root.6.20_inports[ ]
style root.6.20_inports fill:none,stroke:none
end
subgraph root.6.20_outports[ ]
style root.6.20_outports fill:none,stroke:none
end
end
subgraph root.6.21[<center>UnaryOperator<br/>Ceil</center>]
subgraph root.6.21_inports[ ]
style root.6.21_inports fill:none,stroke:none
end
subgraph root.6.21_outports[ ]
style root.6.21_outports fill:none,stroke:none
end
end
subgraph root.6.22[<center>Decider<br/>GT for 0s</center>]
subgraph root.6.22_inports[ ]
style root.6.22_inports fill:none,stroke:none
end
subgraph root.6.22_outports[ ]
style root.6.22_outports fill:none,stroke:none
end
end
subgraph root.6.23[Switcher]
subgraph root.6.23_inports[ ]
style root.6.23_inports fill:none,stroke:none
end
subgraph root.6.23_outports[ ]
style root.6.23_outports fill:none,stroke:none
end
end
subgraph root.6.24[Max]
subgraph root.6.24_inports[ ]
style root.6.24_inports fill:none,stroke:none
end
subgraph root.6.24_outports[ ]
style root.6.24_outports fill:none,stroke:none
end
end
subgraph root.6.25[Max]
subgraph root.6.25_inports[ ]
style root.6.25_inports fill:none,stroke:none
end
subgraph root.6.25_outports[ ]
style root.6.25_outports fill:none,stroke:none
end
end
subgraph root.6.26[<center>Holder<br/>for: 30s</center>]
subgraph root.6.26_inports[ ]
style root.6.26_inports fill:none,stroke:none
end
subgraph root.6.26_outports[ ]
style root.6.26_outports fill:none,stroke:none
end
end
subgraph root.6.27[<center>Holder<br/>for: 40s</center>]
subgraph root.6.27_inports[ ]
style root.6.27_inports fill:none,stroke:none
end
subgraph root.6.27_outports[ ]
style root.6.27_outports fill:none,stroke:none
end
end
FakeConstant14((1.50))
FakeConstant14 --> root.6.28rhs
subgraph root.6.28[<center>ArithmeticCombinator<br/>Mul</center>]
subgraph root.6.28_inports[ ]
style root.6.28_inports fill:none,stroke:none
root.6.28rhs[rhs]
end
subgraph root.6.28_outports[ ]
style root.6.28_outports fill:none,stroke:none
end
end
subgraph root.6.29[<center>Decider<br/>GT for 0s</center>]
subgraph root.6.29_inports[ ]
style root.6.29_inports fill:none,stroke:none
end
subgraph root.6.29_outports[ ]
style root.6.29_outports fill:none,stroke:none
end
end
subgraph root.6.30[<center>Holder<br/>for: 40s</center>]
subgraph root.6.30_inports[ ]
style root.6.30_inports fill:none,stroke:none
end
subgraph root.6.30_outports[ ]
style root.6.30_outports fill:none,stroke:none
end
end
subgraph root.6.31[FirstValid]
subgraph root.6.31_inports[ ]
style root.6.31_inports fill:none,stroke:none
end
subgraph root.6.31_outports[ ]
style root.6.31_outports fill:none,stroke:none
end
end
subgraph root.6.32[FirstValid]
subgraph root.6.32_inports[ ]
style root.6.32_inports fill:none,stroke:none
end
subgraph root.6.32_outports[ ]
style root.6.32_outports fill:none,stroke:none
end
end
subgraph root.6.33[Max]
subgraph root.6.33_inports[ ]
style root.6.33_inports fill:none,stroke:none
end
subgraph root.6.33_outports[ ]
style root.6.33_outports fill:none,stroke:none
end
end
subgraph root.6.34.ScaleReporter[<center>ScaleReporter<br/>default</center>]
subgraph root.6.34.ScaleReporter_outports[ ]
style root.6.34.ScaleReporter_outports fill:none,stroke:none
end
end
subgraph root.6.34.ScaleActuator[<center>ScaleActuator<br/>default</center>]
subgraph root.6.34.ScaleActuator_inports[ ]
style root.6.34.ScaleActuator_inports fill:none,stroke:none
end
end
subgraph root.6.35[NestedSignalEgress]
subgraph root.6.35_inports[ ]
style root.6.35_inports fill:none,stroke:none
end
end
subgraph root.6.36[NestedSignalEgress]
subgraph root.6.36_inports[ ]
style root.6.36_inports fill:none,stroke:none
end
end
subgraph root.6.37[NestedSignalEgress]
subgraph root.6.37_inports[ ]
style root.6.37_inports fill:none,stroke:none
end
end
