{
 "title": "Jsonnet / FluxNinja",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "FluxMeter",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(flux_meter_sum{valid=\"true\", flow_status=\"OK\", flux_meter_name=\"example\"}[$__rate_interval]))\n/ sum(increase(flux_meter_count{valid=\"true\", flow_status=\"OK\", flux_meter_name=\"example\"}[$__rate_interval]))\n"
    }
   ]
  },
  {
   "title": "Workload Decisions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(workload_index, decision_type) (rate(workload_requests_total{policy_name=\"example\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Workload Latency (Auto Tokens)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum by (workload_index) (increase(workload_latency_ms_sum{policy_name=\"example\"}[$__rate_interval])))/(sum by (workload_index) (increase(workload_latency_ms_count{policy_name=\"example\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Incoming Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(incoming_work_seconds_total{policy_name=\"example\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Accepted Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(accepted_work_seconds_total{policy_name=\"example\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "WFQ Scheduler Flows",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(wfq_flows_total{policy_name=\"example\"})",
     "legendFormat": "{{ instance }} - {{ policy_name }}"
    }
   ]
  },
  {
   "title": "Average Load Multiplier",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(token_bucket_lm_ratio{policy_name=\"example\"})",
     "legendFormat": "{{ instance }} - {{ policy_name }}"
    }
   ]
  },
  {
   "title": "Token Bucket Bucket Capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(token_bucket_capacity_total{policy_name=\"example\"})",
     "legendFormat": "{{ instance }} - {{ policy_name }}"
    }
   ]
  },
  {
   "title": "Token Bucket Bucket FillRate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(token_bucket_fill_rate{policy_name=\"example\"})",
     "legendFormat": "{{ instance }} - {{ policy_name }}"
    }
   ]
  },
  {
   "title": "Token Bucket Available Tokens",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(token_bucket_available_tokens_total{policy_name=\"example\"})",
     "legendFormat": "{{ instance }} - {{ policy_name }}"
    }
   ]
  },
  {
   "title": "WFQ Scheduler Heap Requests",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(wfq_requests_total{policy_name=\"example\"})",
     "legendFormat": "{{ instance }} - {{ policy_name }}"
    }
   ]
  }
 ]
}