flowchart LR
    subgraph agent["Aperture Agent"]
        subgraph sd["Service discovery"]
        end
        subgraph metrics["Metrics Service"]
        end
        subgraph fcs["Dataplane Service"]
            classifiers["Classifiers"]
            actuators["Actuators"]
            fluxmeters["Flux Meters"]
        end
    end
    subgraph controller["Aperture Controller"]
        mgmt[Policy Management]
        loop[Policy Control Loop]
    end
    subgraph mesh["Service Mesh"]
    end
    db[("Metrics DB")]
    mgmt-->|configs| fcs
    loop-->|decisions| actuators
    mesh -->|metrics| metrics
    mesh -->|service metadata| sd
    mesh <-->|flows| fcs
    actuators -->|metrics| db
    metrics -->|metrics| db
    db --> loop
