flowchart TD
    blueprints[/"Blueprints"/]
    policies[/"Policies"/]
    subgraph controller["Aperture Controller"]
        circuit["Control Circuit"]
    end
    subgraph databases["Aperture Databases"]
      prometheus[("Prometheus")]
      etcd[("etcd")]
    end
    subgraph discoverydb["Discovery Databases"]
      k8sdiscovery["Kubernetes"]
      consul["Consul"]
    end
    subgraph orchestrators["Orchestrators"]
      k8s["Kubernetes"]
    end
    subgraph worker["Worker Node (Kubernetes/VM/Bare-metal)"]
      subgraph agent["Aperture Agent"]
          discovery["Discovery"]
          telemetry["Telemetry Collector"]
          flowcontrol["Flow Controller"]
          autoscaler["Auto Scaler"]
      end
      subgraph serviceinstance["Service Instance"]
        servicelogic["Service Logic"]
        servicemesh["Service Mesh"]
      end
      subgraph gateways["Gateways"]
        Kong["Kong"]
        Nginx["Nginx"]
      end
    end
    blueprints --> |aperturectl| policies
    policies --> |Kubernetes Custom Resource| controller
    controller<--> |Configuration/Telemetry/Flow Control| databases
    databases<-->|Configuration/Telemetry/Flow Control|agent
    agent <--->|SDK: Telemetry/Flow Control| servicelogic
    agent <--->|Telemetry/Flow Control| servicemesh
		agent <--->|Telemetry/Flow Control| gateways
    orchestrators <-->|Auto Scale| agent
    discoverydb <-->|Discovery| agent
