flowchart
  subgraph User VPC
    direction TB
    subgraph Controller["Aperture Controller"]
      ControlLoop["Policy Control Loop"]
      PolicyManagement["Classification Rules\n& Policy Management"]
    end
    subgraph ControllerDB["Aperture Data"]
      MetricsDB[("High-frequency short-scale\nmetrics DB")]
      ETCD[("K/V Store")]
    end
    subgraph KubernetesNode["Kubernetes Node"]
      subgraph Agent["Aperture Agent"]
        subgraph AgentMetricsService["Metrics Service"]
          direction LR
          AgentDiscovery["Service Discovery"]
          AgentMetrics["Metrics Collection"]
        end
        subgraph AgentFlowControl["Flow Control Service"]
          direction LR
          ConcurrencyControl["Concurrency Control"]
          Quotas["API Quotas"]
        end
        subgraph AgentClass["Classification Service"]
        end
      end
      subgraph ServiceAPod["Service A Pod"]
        subgraph ServiceA["Service A"]
          FeaturesA{{"Features & Frameworks\n(user code)"}}
          LibraryA["Aperture Library"]
        end
        MeshA["Service Mesh Dataplane Proxy"]
      end
      subgraph ServiceBPod["Service B Pod"]
        MeshB["Service Mesh Dataplane Proxy"]
      end
    end
  end

%% Agent --> Cloud
%% Controller <--> Cloud
Controller <--> ETCD
MetricsDB --> Controller

ETCD --> Agent
Agent --> MetricsDB
ServiceA <-..-> MeshA

MeshA <--Decisions & metadata--> Agent

MeshA <-. API Traffic .-> MeshB

FeaturesA <--> LibraryA
LibraryA <-- Decisions & metadata --> Agent
Quotas <-- "shared counters synchronization\nwith other agents' quotas" --> Quotas
