flowchart LR
subgraph root.11[ConcurrencyLimiter]
subgraph root.11_inports[ ]
style root.11_inports fill:none,stroke:none
root.11load_multiplier[load_multiplier]
end
subgraph root.11_outports[ ]
style root.11_outports fill:none,stroke:none
root.11accepted_concurrency[accepted_concurrency]
root.11incoming_concurrency[incoming_concurrency]
end
end
