{
 "title": "Aperture Service Protection for PostgreSQL",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Quota Checks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(decision_type) (rate(workload_requests_total{policy_name=\"postgres-connections\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Workload Decisions (accepted)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(workload_index, decision_type) (rate(workload_requests_total{policy_name=\"postgres-connections\",decision_type=\"DECISION_TYPE_ACCEPTED\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Workload Decisions (rejected)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(workload_index, decision_type) (rate(workload_requests_total{policy_name=\"postgres-connections\",decision_type=\"DECISION_TYPE_REJECTED\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Workload Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum by (workload_index) (increase(workload_latency_ms_sum{policy_name=\"postgres-connections\"}[$__rate_interval])))/(sum by (workload_index) (increase(workload_latency_ms_count{policy_name=\"postgres-connections\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Request in Queue Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum by (component_id) (increase(request_in_queue_duration_ms_sum{policy_name=\"postgres-connections\"}[$__rate_interval])))/(sum by (component_id) (increase(request_in_queue_duration_ms_count{policy_name=\"postgres-connections\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Incoming Token Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum(rate(incoming_tokens_total{policy_name=\"postgres-connections\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Accepted Token Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum(rate(accepted_tokens_total{policy_name=\"postgres-connections\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "WFQ Scheduler Flows",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "y": 70 },
   "targets": [
    {
     "expr": "avg(wfq_flows_total{policy_name=\"postgres-connections\"})"
    }
   ]
  },
  {
   "title": "WFQ Scheduler Heap Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "avg(wfq_requests_total{policy_name=\"postgres-connections\"})"
    }
   ]
  },
  {
   "title": "Average Load Multiplier",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(token_bucket_lm_ratio{policy_name=\"postgres-connections\"})",
     "legendFormat": "{{ instance }} - {{ policy_name }}"
    }
   ]
  },
  {
   "title": "Token Bucket Capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(token_bucket_capacity_total{policy_name=\"postgres-connections\"})",
     "legendFormat": "{{ instance }} - {{ policy_name }}"
    }
   ]
  },
  {
   "title": "Token Bucket FillRate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(token_bucket_fill_rate{policy_name=\"postgres-connections\"})",
     "legendFormat": "{{ instance }} - {{ policy_name }}"
    }
   ]
  },
  {
   "title": "Token Bucket Available Tokens",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(token_bucket_available_tokens_total{policy_name=\"postgres-connections\"})",
     "legendFormat": "{{ instance }} - {{ policy_name }}"
    }
   ]
  },
  {
   "title": "Query for SIGNAL",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24 },
   "targets": [
    {
     "expr": "(sum(postgresql_backends{policy_name=\"postgres-connections\",infra_meter_name=\"postgresql\"}) / sum(postgresql_connection_max{policy_name=\"postgres-connections\",infra_meter_name=\"postgresql\"})) * 100"
    }
   ]
  }
 ]
}