{
 "title": "Aperture Service Protection for PostgreSQL",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "PGSQL Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(postgresql_database_count{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\"})",
     "legendFormat": "{{ instance }} - {{ policy_name }}"
    }
   ]
  },
  {
   "title": "PGSQL Instances Size (GB)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(postgresql_db_size_bytes{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\"}) / 1024 / 1024 / 1024",
     "legendFormat": "{{ instance }} - {{ policy_name }}"
    }
   ]
  },
  {
   "title": "Number of tables",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(postgresql_table_count{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\"})",
     "legendFormat": "{{ instance }} - {{ policy_name }}"
    }
   ]
  },
  {
   "title": "Tables Size (MB) ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(postgresql_table_size_bytes{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\"}) / 1024 / 1024",
     "legendFormat": "{{ instance }} - {{ policy_name }}"
    }
   ]
  },
  {
   "title": "Table cache hit rate %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(postgresql_blocks_read_total{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\",source=\"heap_hit\"}) / (sum(postgresql_blocks_read_total{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\",source=\"heap_hit\"}) + sum(postgresql_blocks_read_total{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\",source=\"heap_read\"}))",
     "legendFormat": "{{ instance }} - {{ policy_name }}"
    }
   ]
  },
  {
   "title": "Index cache hit rate %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(postgresql_blocks_read_total{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\",source=\"idx_hit\"}) / (sum(postgresql_blocks_read_total{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\",source=\"idx_hit\"}) + sum(postgresql_blocks_read_total{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\",source=\"idx_read\"}))",
     "legendFormat": "{{ instance }} - {{ policy_name }}"
    }
   ]
  },
  {
   "title": "Active Connections %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(postgresql_backends{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\"}) / sum(postgresql_connection_max{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\"}) * 100",
     "legendFormat": "{{ instance }} - {{ policy_name }}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgresql_connection_max{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\"} / postgresql_database_count",
     "legendFormat": "{{ instance }} - {{ policy_name }}"
    }
   ]
  },
  {
   "title": "Commits vs Rollbacks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(postgresql_commits_total{policy_name=\"postgres-connections\", infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\"}[$__rate_interval])",
     "legendFormat": "Commits"
    },
    {
     "expr": "rate(postgresql_rollbacks_total{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\"}[$__rate_interval])",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by (operation) (rate(postgresql_operations_total{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\",operation=\"ins\"}[$__rate_interval]))",
     "legendFormat": "Insert"
    },
    {
     "expr": "sum by (operation) (rate(postgresql_operations_total{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\",operation=\"del\"}[$__rate_interval]))",
     "legendFormat": "Delete"
    },
    {
     "expr": "sum by (operation) (rate(postgresql_operations_total{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\",operation=\"upd\"}[$__rate_interval]))",
     "legendFormat": "Update"
    },
    {
     "expr": "sum by (operation) (rate(postgresql_operations_total{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\",operation=\"hot_upd\"}[$__rate_interval]))",
     "legendFormat": "Hot Update"
    }
   ]
  },
  {
   "title": "Heap Read vs Index Read",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(postgresql_blocks_read_total{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\",source=\"heap_read\"}[$__rate_interval]))",
     "legendFormat": "Heap Read"
    },
    {
     "expr": "sum(rate(postgresql_blocks_read_total{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\",source=\"idx_read\"}[$__rate_interval]))",
     "legendFormat": "Index Read"
    }
   ]
  },
  {
   "title": "Checkpoint Scheduled vs Requested",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(postgresql_bgwriter_checkpoint_count_total{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\",type=\"requested\"}[$__rate_interval]))",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(rate(postgresql_bgwriter_checkpoint_count_total{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\",type=\"scheduled\"}[$__rate_interval]))",
     "legendFormat": "Scheduled"
    }
   ]
  },
  {
   "title": "Tables with most live rows",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "topk(5, sum by (postgresql_table_name,postgresql_database_name) (postgresql_rows{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\",state=\"live\"}))"
    }
   ]
  },
  {
   "title": "Tables with most disk usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "topk(5, sum by (postgresql_table_name,postgresql_database_name) (postgresql_table_size_bytes{policy_name=\"postgres-connections\",infra_meter_name=\"{\"agent_group\": \"default\", \"per_agent_group\": true, \"receivers\": {\"postgresql\": {\"collection_interval\": \"1s\", \"databases\": [\"postgres\"], \"endpoint\": \"postgresql.postgresql.svc.cluster.local:5432\", \"password\": \"secretpassword\", \"tls\": {\"insecure\": true}, \"username\": \"postgres\"}}}\"}))"
    }
   ]
  }
 ]
}