#!/usr/bin/env bash

set -euo pipefail
set -x

settable_env_vars=(
  VERSION
  GIT_BRANCH
  GIT_COMMIT_HASH
  REF
  SHA256
)

get_tarball() {
  local -r ref="${1?Ref missing}"
  curl -L https://api.github.com/repos/fluxninja/aperture/tarball/"${ref}"
}

# shellcheck disable=SC2034
GIT_BRANCH="$(git branch --show-current)"
# shellcheck disable=SC2034
GIT_COMMIT_HASH="$(git log -n1 --format=%H)"

REF="v${VERSION:-}"
# shellcheck disable=SC2034
SHA256="$(get_tarball "${REF}" | sha256sum | cut -d ' ' -f1)"

for var_name in "${settable_env_vars[@]}"; do
  if [ -z "${!var_name}" ]; then
    printf 'Variable %s is required but not set!\n' "${var_name}" >&2
    exit 1
  fi
done

export "${settable_env_vars[@]}"

# Limit envsubst to only replace variables we want
shell_format_vars="\$${settable_env_vars[*]}"
shell_format_vars="${shell_format_vars// / $}"

for template in "${TAP_REPO?Missing tap repo}"/Formula/*.template; do
  formula="${template%%.template}"
  {
    printf '### DO NOT EDIT THIS FILE ###\n'
    printf '### This file was automatically generated and changes will be lost!\n'
    printf '### To make changes, edit %s instead.\n\n' "${template##*/}"
    envsubst "${shell_format_vars}" <"${template}"
  } >"${formula}"
done
