flowchart LR
subgraph root.0[<center>AIADLoadScheduler<br/>1 selectors</center>]
subgraph root.0_inports[ ]
style root.0_inports fill:none,stroke:none
root.0overload_confirmation[overload_confirmation]
root.0setpoint[setpoint]
root.0signal[signal]
end
subgraph root.0_outports[ ]
style root.0_outports fill:none,stroke:none
end
end
root.0_overload_confirmation_FakeConstantout((1.00))
subgraph root.1[<center>PromQL<br/>every 0s</center>]
subgraph root.1_outports[ ]
style root.1_outports fill:none,stroke:none
root.1output[output]
end
end
root.2output((40.00))
root.0_overload_confirmation_FakeConstantout --> root.0overload_confirmation
root.1output --> |SIGNAL| root.0signal
root.2output --> |SETPOINT| root.0setpoint
